# Generated by Django 5.0.7 on 2025-12-09 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_attempt_options_alter_attempt_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttemptDependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=200, null=True)),
                ('nachtakt_attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vortakt_attempts', to='api.attempt')),
                ('vortakt_attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nachtakt_attempts', to='api.attempt')),
            ],
            options={
                'unique_together': {('vortakt_attempt', 'nachtakt_attempt')},
            },
        ),
    ]
