# Generated by Django 5.0.7 on 2025-12-09 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_attemptdependency'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='slot_index',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
