# Generated by Django 5.2.6 on 2025-12-12 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_task_project_alter_team_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='line_index',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
